"""
Copyright (c) CMB/EB 2023, All Rights Reserved 

THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED 
IN THIS NOTICE BE LIABLE FOR ANY CLAIM OR CONSEQUENTIAL DAMAGES OR ANY 
DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Author Taylor Lopes <taylor.lopes@eb.mil.br>
""" 

# Configuração da aplicação
import os
import pytz

# Debug
FLASK_DEBUG = False

# Timezone
TIMEZONE = pytz.timezone('America/Sao_Paulo')

# Nome da aplicação
APP_NAME = 'CMB'

# Chave secreta da aplicação
SECRET_KEY=os.environ.get('SECRET_KEY')

# Desabilita cache de templates
TEMPLATES_AUTO_RELOAD = True 

# Tempo de expiração do token WTF
WTF_CSRF_TIME_LIMIT = 259200 # 72h